In [1]:
import numpy as np

In [116]:
a = np.array([1,9,3,4])
b = np.array([1,2,3,4]) - 1
c = np.array([5,2,1,-4])
d = np.array([7,3,0,5])

In [54]:
a.reshape((1, -1))

array([[1, 2, 3, 4]])

In [181]:
trials = 50000

In [182]:
for _ in range(trials):
    a = np.random.random(4)
    b = np.random.random(4)
    c = np.random.random(4)
    d = np.random.random(4)
    res = a * b[:, None] * c[:, None, None] * d[:, None, None, None]
    # res = a[:, None, None, None] * b[:, None, None] * c[:, None] * d

In [184]:
for i in range(4):
    for j in range(4):
        for k in range(4):
            for m in range(4):
                assert res[i,j,k,m] == a[m]*b[k]*c[j]*d[i]

In [152]:
for _ in range(trials):
    a = np.random.random(4)
    b = np.random.random(4)
    c = np.random.random(4)
    d = np.random.random(4)

    for i in range(4):
        for j in range(4):
            for k in range(4):
                for m in range(4):
                    _resi = a[m]*b[k]*c[j]*d[i]

In [158]:
np.where(res > 0.01)[0].shape

(135,)

In [157]:
res[0]

array([[[0.00711374, 0.0518134 , 0.01053082, 0.00991789],
        [0.00394904, 0.02876309, 0.00584596, 0.0055057 ],
        [0.00246858, 0.01798005, 0.00365436, 0.00344166],
        [0.00141344, 0.01029486, 0.00209238, 0.0019706 ]],

       [[0.00524931, 0.03823371, 0.00777081, 0.00731852],
        [0.00291404, 0.02122462, 0.0043138 , 0.00406272],
        [0.00182159, 0.01326769, 0.00269659, 0.00253964],
        [0.00104299, 0.0075967 , 0.00154399, 0.00145413]],

       [[0.00720602, 0.05248556, 0.01066743, 0.01004655],
        [0.00400027, 0.02913623, 0.0059218 , 0.00557712],
        [0.0025006 , 0.0182133 , 0.00370176, 0.00348631],
        [0.00143177, 0.01042842, 0.00211952, 0.00199616]],

       [[0.00523639, 0.03813958, 0.00775168, 0.0073005 ],
        [0.00290687, 0.02117236, 0.00430318, 0.00405272],
        [0.00181711, 0.01323502, 0.00268995, 0.00253339],
        [0.00104042, 0.007578  , 0.00154019, 0.00145055]]])

In [177]:
A = np.random.random((4, 4))
print(A)
a, b, c, d = A

[[0.86926353 0.02534617 0.95394669 0.74632641]
 [0.74662726 0.05896299 0.0658278  0.66951944]
 [0.63537999 0.01559207 0.28320143 0.75474345]
 [0.37218221 0.13571921 0.84412736 0.2942924 ]]


In [179]:
a, b, c, d

(array([0.86926353, 0.02534617, 0.95394669, 0.74632641]),
 array([0.74662726, 0.05896299, 0.0658278 , 0.66951944]),
 array([0.63537999, 0.01559207, 0.28320143, 0.75474345]),
 array([0.37218221, 0.13571921, 0.84412736, 0.2942924 ]))